// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/user/protobuf/user.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//------------------------------------------------------------------------------------------------------------------
//  SignUp
//------------------------------------------------------------------------------------------------------------------
type SignUpRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=LastName,proto3" json:"LastName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eafa52feaf4acb56, []int{0}
}

func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (m *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(m, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

func (m *SignUpRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignUpRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SignUpRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *SignUpRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type SignUpResponse struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=Slug,proto3" json:"Slug,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Role                 string   `protobuf:"bytes,3,opt,name=Role,proto3" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpResponse) Reset()         { *m = SignUpResponse{} }
func (m *SignUpResponse) String() string { return proto.CompactTextString(m) }
func (*SignUpResponse) ProtoMessage()    {}
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eafa52feaf4acb56, []int{1}
}

func (m *SignUpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpResponse.Unmarshal(m, b)
}
func (m *SignUpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpResponse.Marshal(b, m, deterministic)
}
func (m *SignUpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpResponse.Merge(m, src)
}
func (m *SignUpResponse) XXX_Size() int {
	return xxx_messageInfo_SignUpResponse.Size(m)
}
func (m *SignUpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpResponse proto.InternalMessageInfo

func (m *SignUpResponse) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *SignUpResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignUpResponse) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

//------------------------------------------------------------------------------------------------------------------
//  SignIn
//------------------------------------------------------------------------------------------------------------------
type SignInRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eafa52feaf4acb56, []int{2}
}

func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (m *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(m, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignInRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignInResponse struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=Slug,proto3" json:"Slug,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Role                 string   `protobuf:"bytes,3,opt,name=Role,proto3" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInResponse) Reset()         { *m = SignInResponse{} }
func (m *SignInResponse) String() string { return proto.CompactTextString(m) }
func (*SignInResponse) ProtoMessage()    {}
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eafa52feaf4acb56, []int{3}
}

func (m *SignInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInResponse.Unmarshal(m, b)
}
func (m *SignInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInResponse.Marshal(b, m, deterministic)
}
func (m *SignInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInResponse.Merge(m, src)
}
func (m *SignInResponse) XXX_Size() int {
	return xxx_messageInfo_SignInResponse.Size(m)
}
func (m *SignInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignInResponse proto.InternalMessageInfo

func (m *SignInResponse) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *SignInResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignInResponse) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

//------------------------------------------------------------------------------------------------------------------
//  LogOut
//------------------------------------------------------------------------------------------------------------------
type LogOutRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogOutRequest) Reset()         { *m = LogOutRequest{} }
func (m *LogOutRequest) String() string { return proto.CompactTextString(m) }
func (*LogOutRequest) ProtoMessage()    {}
func (*LogOutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eafa52feaf4acb56, []int{4}
}

func (m *LogOutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogOutRequest.Unmarshal(m, b)
}
func (m *LogOutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogOutRequest.Marshal(b, m, deterministic)
}
func (m *LogOutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogOutRequest.Merge(m, src)
}
func (m *LogOutRequest) XXX_Size() int {
	return xxx_messageInfo_LogOutRequest.Size(m)
}
func (m *LogOutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogOutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogOutRequest proto.InternalMessageInfo

func (m *LogOutRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LogOutResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogOutResponse) Reset()         { *m = LogOutResponse{} }
func (m *LogOutResponse) String() string { return proto.CompactTextString(m) }
func (*LogOutResponse) ProtoMessage()    {}
func (*LogOutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eafa52feaf4acb56, []int{5}
}

func (m *LogOutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogOutResponse.Unmarshal(m, b)
}
func (m *LogOutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogOutResponse.Marshal(b, m, deterministic)
}
func (m *LogOutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogOutResponse.Merge(m, src)
}
func (m *LogOutResponse) XXX_Size() int {
	return xxx_messageInfo_LogOutResponse.Size(m)
}
func (m *LogOutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogOutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogOutResponse proto.InternalMessageInfo

func (m *LogOutResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

//------------------------------------------------------------------------------------------------------------------
//  CREATE
//------------------------------------------------------------------------------------------------------------------
type CreateUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`
	FirstName            string   `protobuf:"bytes,5,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,6,opt,name=LastName,proto3" json:"LastName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eafa52feaf4acb56, []int{6}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CreateUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreateUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type CreateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eafa52feaf4acb56, []int{7}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

//------------------------------------------------------------------------------------------------------------------
//  UPDATE
//------------------------------------------------------------------------------------------------------------------
type UpdateUserRequest struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=Slug,proto3" json:"Slug,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`
	FirstName            string   `protobuf:"bytes,5,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,6,opt,name=LastName,proto3" json:"LastName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eafa52feaf4acb56, []int{8}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *UpdateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UpdateUserRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UpdateUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UpdateUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type UpdateUserResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eafa52feaf4acb56, []int{9}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

//------------------------------------------------------------------------------------------------------------------
//  DELETE
//------------------------------------------------------------------------------------------------------------------
type DeleteUserRequest struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=Slug,proto3" json:"Slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eafa52feaf4acb56, []int{10}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type DeleteUserResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eafa52feaf4acb56, []int{11}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

func (m *DeleteUserResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

//------------------------------------------------------------------------------------------------------------------
//  GET
//------------------------------------------------------------------------------------------------------------------
type GetUserRequest struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=Slug,proto3" json:"Slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eafa52feaf4acb56, []int{12}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eafa52feaf4acb56, []int{13}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

//------------------------------------------------------------------------------------------------------------------
//  FIND USERS
//------------------------------------------------------------------------------------------------------------------
type FindUserRequest struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=Slug,proto3" json:"Slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindUserRequest) Reset()         { *m = FindUserRequest{} }
func (m *FindUserRequest) String() string { return proto.CompactTextString(m) }
func (*FindUserRequest) ProtoMessage()    {}
func (*FindUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eafa52feaf4acb56, []int{14}
}

func (m *FindUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserRequest.Unmarshal(m, b)
}
func (m *FindUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserRequest.Marshal(b, m, deterministic)
}
func (m *FindUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserRequest.Merge(m, src)
}
func (m *FindUserRequest) XXX_Size() int {
	return xxx_messageInfo_FindUserRequest.Size(m)
}
func (m *FindUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserRequest proto.InternalMessageInfo

func (m *FindUserRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type FindUserResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=Users,proto3" json:"Users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindUserResponse) Reset()         { *m = FindUserResponse{} }
func (m *FindUserResponse) String() string { return proto.CompactTextString(m) }
func (*FindUserResponse) ProtoMessage()    {}
func (*FindUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eafa52feaf4acb56, []int{15}
}

func (m *FindUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserResponse.Unmarshal(m, b)
}
func (m *FindUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserResponse.Marshal(b, m, deterministic)
}
func (m *FindUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserResponse.Merge(m, src)
}
func (m *FindUserResponse) XXX_Size() int {
	return xxx_messageInfo_FindUserResponse.Size(m)
}
func (m *FindUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserResponse proto.InternalMessageInfo

func (m *FindUserResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

//------------------------------------------------------------------------------------------------------------------
//  USER
//------------------------------------------------------------------------------------------------------------------
type User struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Slug                 string   `protobuf:"bytes,2,opt,name=Slug,proto3" json:"Slug,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	FirstName            string   `protobuf:"bytes,5,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,6,opt,name=LastName,proto3" json:"LastName,omitempty"`
	Phone                string   `protobuf:"bytes,7,opt,name=Phone,proto3" json:"Phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_eafa52feaf4acb56, []int{16}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func init() {
	proto.RegisterType((*SignUpRequest)(nil), "protobuf.SignUpRequest")
	proto.RegisterType((*SignUpResponse)(nil), "protobuf.SignUpResponse")
	proto.RegisterType((*SignInRequest)(nil), "protobuf.SignInRequest")
	proto.RegisterType((*SignInResponse)(nil), "protobuf.SignInResponse")
	proto.RegisterType((*LogOutRequest)(nil), "protobuf.LogOutRequest")
	proto.RegisterType((*LogOutResponse)(nil), "protobuf.LogOutResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "protobuf.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "protobuf.CreateUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "protobuf.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "protobuf.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "protobuf.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "protobuf.DeleteUserResponse")
	proto.RegisterType((*GetUserRequest)(nil), "protobuf.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "protobuf.GetUserResponse")
	proto.RegisterType((*FindUserRequest)(nil), "protobuf.FindUserRequest")
	proto.RegisterType((*FindUserResponse)(nil), "protobuf.FindUserResponse")
	proto.RegisterType((*User)(nil), "protobuf.User")
}

func init() { proto.RegisterFile("services/user/protobuf/user.proto", fileDescriptor_eafa52feaf4acb56) }

var fileDescriptor_eafa52feaf4acb56 = []byte{
	// 619 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x95, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xeb, 0xc4, 0x0e, 0xed, 0x54, 0x4d, 0xe9, 0x52, 0xa0, 0xb8, 0x39, 0xc0, 0xaa, 0x15,
	0x3d, 0xa0, 0x44, 0x14, 0x21, 0xf5, 0x80, 0xc4, 0x01, 0xda, 0xa8, 0x52, 0x05, 0x55, 0xd2, 0x48,
	0x5c, 0x5d, 0xb2, 0x18, 0x0b, 0x77, 0xd7, 0x78, 0xd7, 0xe5, 0x0c, 0xaf, 0xc0, 0x53, 0x70, 0xe4,
	0xc6, 0x7b, 0xf0, 0x0a, 0xdc, 0x79, 0x05, 0xb4, 0xbb, 0xde, 0x78, 0xfd, 0x87, 0x84, 0x0a, 0x24,
	0x6e, 0x19, 0xcf, 0xf8, 0xb7, 0xdf, 0x78, 0x76, 0xbe, 0xc0, 0x3d, 0x4e, 0xd2, 0xcb, 0xe8, 0x35,
	0xe1, 0x83, 0x8c, 0x93, 0x74, 0x90, 0xa4, 0x4c, 0xb0, 0xf3, 0xec, 0x8d, 0x8a, 0xfa, 0x2a, 0x42,
	0xcb, 0xe6, 0xa1, 0xdf, 0x0b, 0x19, 0x0b, 0x63, 0x32, 0x08, 0x92, 0x68, 0x10, 0x50, 0xca, 0x44,
	0x20, 0x22, 0x46, 0xb9, 0xae, 0xc3, 0x1f, 0x1d, 0x58, 0x1b, 0x47, 0x21, 0x9d, 0x24, 0x23, 0xf2,
	0x3e, 0x23, 0x5c, 0x20, 0x1f, 0x96, 0x27, 0x9c, 0xa4, 0x34, 0xb8, 0x20, 0x5b, 0xce, 0x5d, 0x67,
	0x6f, 0x65, 0x34, 0x8b, 0x65, 0xee, 0x34, 0xe0, 0xfc, 0x03, 0x4b, 0xa7, 0x5b, 0x2d, 0x9d, 0x33,
	0x31, 0xea, 0xc1, 0xca, 0x51, 0x94, 0x72, 0xf1, 0x42, 0xbe, 0xd8, 0x56, 0xc9, 0xe2, 0x81, 0x7c,
	0xf3, 0x24, 0xc8, 0x93, 0xae, 0x7e, 0xd3, 0xc4, 0xf8, 0x0c, 0xba, 0x46, 0x02, 0x4f, 0x18, 0xe5,
	0x04, 0x21, 0x70, 0xc7, 0x71, 0x16, 0xe6, 0xe7, 0xab, 0xdf, 0x25, 0x5d, 0xad, 0x8a, 0x2e, 0x04,
	0xee, 0x88, 0xc5, 0xe6, 0x58, 0xf5, 0x1b, 0x0f, 0x75, 0x63, 0xc7, 0xf4, 0x2f, 0x1b, 0x33, 0xf2,
	0x24, 0xe8, 0x1f, 0xca, 0xdb, 0x85, 0xb5, 0x13, 0x16, 0xbe, 0xcc, 0x84, 0x91, 0xb7, 0x09, 0xde,
	0x19, 0x7b, 0x47, 0x68, 0x4e, 0xd5, 0x01, 0xde, 0x83, 0xae, 0x29, 0xcb, 0x0f, 0xbf, 0x05, 0x9d,
	0xb1, 0x08, 0x44, 0xc6, 0x55, 0xa1, 0x37, 0xca, 0x23, 0xfc, 0xd5, 0x81, 0x8d, 0x67, 0x29, 0x09,
	0x04, 0x91, 0xe7, 0xfe, 0x49, 0xd3, 0x9b, 0xe0, 0x1d, 0x5e, 0x04, 0x51, 0x9c, 0xeb, 0xd5, 0x41,
	0xe9, 0x53, 0xb4, 0x2b, 0x33, 0xde, 0x04, 0xef, 0xf4, 0x2d, 0xa3, 0x66, 0x84, 0x3a, 0x28, 0x4f,
	0xde, 0x9b, 0x37, 0xf9, 0x4e, 0x65, 0xf2, 0x07, 0x80, 0x6c, 0xc9, 0x79, 0x87, 0x18, 0x5c, 0x19,
	0x2b, 0xbd, 0xab, 0xfb, 0xdd, 0xbe, 0xb9, 0xca, 0x7d, 0x55, 0xa5, 0x72, 0xf8, 0x8b, 0x03, 0x1b,
	0x93, 0x64, 0x5a, 0xe9, 0xb6, 0x69, 0x30, 0xff, 0xbf, 0xcb, 0x07, 0x80, 0x6c, 0xa9, 0x0b, 0xe6,
	0x78, 0x1f, 0x36, 0x9e, 0x93, 0x98, 0x2c, 0x6c, 0x4c, 0x62, 0xed, 0xc2, 0x05, 0xd8, 0x1d, 0xe8,
	0x0e, 0x89, 0x58, 0xc4, 0x7c, 0x0c, 0xeb, 0xb3, 0xaa, 0x2b, 0x4c, 0x63, 0x17, 0xd6, 0x8f, 0x22,
	0x3a, 0x5d, 0x44, 0x3f, 0x80, 0xeb, 0x45, 0x59, 0x8e, 0xdf, 0x01, 0x4f, 0xc6, 0x52, 0x6e, 0xbb,
	0x81, 0xaf, 0x93, 0xf8, 0x9b, 0xa3, 0x55, 0xcc, 0xbd, 0xcf, 0xe6, 0xc8, 0x56, 0xd3, 0xf4, 0xdb,
	0xbf, 0x9b, 0xbe, 0x3b, 0xcf, 0xc7, 0xae, 0x32, 0xe7, 0xe2, 0xde, 0x5c, 0xb3, 0xee, 0xcd, 0xfe,
	0x4f, 0x17, 0x56, 0xa5, 0xc4, 0xb1, 0xf6, 0x6c, 0xf4, 0x0a, 0x3a, 0xda, 0xed, 0xd0, 0xed, 0xa2,
	0xd7, 0x92, 0x05, 0xfb, 0x5b, 0xf5, 0x84, 0xfe, 0x5a, 0x78, 0xfb, 0xd3, 0xf7, 0x1f, 0x9f, 0x5b,
	0x37, 0xf1, 0x0d, 0x65, 0xe7, 0x97, 0x0f, 0xf5, 0x1f, 0x00, 0x8f, 0x42, 0x9a, 0x25, 0x86, 0x7c,
	0x4c, 0xab, 0xe4, 0x99, 0x07, 0x56, 0xc9, 0x85, 0xa7, 0xcd, 0x21, 0x47, 0x54, 0x92, 0xb5, 0x0b,
	0xd9, 0xe4, 0x92, 0x7d, 0xd9, 0xe4, 0xb2, 0x61, 0x19, 0x32, 0x2a, 0x93, 0x63, 0x16, 0xb2, 0x4c,
	0xa0, 0x43, 0xe8, 0x68, 0x07, 0x40, 0xdb, 0x05, 0xa0, 0x66, 0x63, 0x7e, 0xaf, 0x39, 0x99, 0x9f,
	0xb0, 0x24, 0x31, 0x7a, 0xc5, 0x6c, 0x4c, 0xcd, 0x1f, 0x6c, 0x4c, 0x7d, 0x23, 0x35, 0x46, 0xaf,
	0x94, 0x8d, 0xa9, 0x6d, 0xa3, 0x8d, 0xa9, 0x6f, 0x20, 0x5e, 0x42, 0x4f, 0xa0, 0x3d, 0x24, 0x02,
	0x59, 0x9f, 0xa4, 0xbc, 0x7a, 0xfe, 0x9d, 0x86, 0xcc, 0xec, 0xed, 0xa7, 0xe0, 0xca, 0x2d, 0x41,
	0x56, 0x51, 0x65, 0xb9, 0x7c, 0xbf, 0x29, 0x65, 0x00, 0xe7, 0x1d, 0x95, 0x7c, 0xf4, 0x2b, 0x00,
	0x00, 0xff, 0xff, 0x58, 0x4d, 0xcb, 0xf9, 0x27, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	//Регистрация пользовател
	SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error)
	//Аутентификация пользовател
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error)
	//Lgout
	LogOut(ctx context.Context, in *LogOutRequest, opts ...grpc.CallOption) (*LogOutResponse, error)
	//------------------------------------------------------------------------------------------------------------------
	//  CRUD методы
	//------------------------------------------------------------------------------------------------------------------
	Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	Update(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	Delete(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	Get(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	Find(ctx context.Context, in *FindUserRequest, opts ...grpc.CallOption) (*FindUserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error) {
	out := new(SignUpResponse)
	err := c.cc.Invoke(ctx, "/protobuf.UserService/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/protobuf.UserService/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) LogOut(ctx context.Context, in *LogOutRequest, opts ...grpc.CallOption) (*LogOutResponse, error) {
	out := new(LogOutResponse)
	err := c.cc.Invoke(ctx, "/protobuf.UserService/LogOut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/protobuf.UserService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Update(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/protobuf.UserService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Delete(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/protobuf.UserService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Get(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/protobuf.UserService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Find(ctx context.Context, in *FindUserRequest, opts ...grpc.CallOption) (*FindUserResponse, error) {
	out := new(FindUserResponse)
	err := c.cc.Invoke(ctx, "/protobuf.UserService/Find", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	//Регистрация пользовател
	SignUp(context.Context, *SignUpRequest) (*SignUpResponse, error)
	//Аутентификация пользовател
	SignIn(context.Context, *SignInRequest) (*SignInResponse, error)
	//Lgout
	LogOut(context.Context, *LogOutRequest) (*LogOutResponse, error)
	//------------------------------------------------------------------------------------------------------------------
	//  CRUD методы
	//------------------------------------------------------------------------------------------------------------------
	Create(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	Update(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	Delete(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	Get(context.Context, *GetUserRequest) (*GetUserResponse, error)
	Find(context.Context, *FindUserRequest) (*FindUserResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) SignUp(ctx context.Context, req *SignUpRequest) (*SignUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}
func (*UnimplementedUserServiceServer) SignIn(ctx context.Context, req *SignInRequest) (*SignInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (*UnimplementedUserServiceServer) LogOut(ctx context.Context, req *LogOutRequest) (*LogOutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogOut not implemented")
}
func (*UnimplementedUserServiceServer) Create(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedUserServiceServer) Update(ctx context.Context, req *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedUserServiceServer) Delete(ctx context.Context, req *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedUserServiceServer) Get(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedUserServiceServer) Find(ctx context.Context, req *FindUserRequest) (*FindUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.UserService/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SignUp(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.UserService/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_LogOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).LogOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.UserService/LogOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).LogOut(ctx, req.(*LogOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.UserService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Create(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.UserService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Update(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.UserService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Delete(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.UserService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Get(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.UserService/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Find(ctx, req.(*FindUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUp",
			Handler:    _UserService_SignUp_Handler,
		},
		{
			MethodName: "SignIn",
			Handler:    _UserService_SignIn_Handler,
		},
		{
			MethodName: "LogOut",
			Handler:    _UserService_LogOut_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _UserService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UserService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UserService_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _UserService_Get_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _UserService_Find_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/user/protobuf/user.proto",
}
