// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/category/protobuf/category.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//------------------------------------------------------------------------------------------------------------------
//  CREATE
//------------------------------------------------------------------------------------------------------------------
type CreateCategoryRequest struct {
	ParentId             string   `protobuf:"bytes,1,opt,name=ParentId,proto3" json:"ParentId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=Path,proto3" json:"Path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCategoryRequest) Reset()         { *m = CreateCategoryRequest{} }
func (m *CreateCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCategoryRequest) ProtoMessage()    {}
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_943ab93be45729ab, []int{0}
}

func (m *CreateCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCategoryRequest.Unmarshal(m, b)
}
func (m *CreateCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCategoryRequest.Marshal(b, m, deterministic)
}
func (m *CreateCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCategoryRequest.Merge(m, src)
}
func (m *CreateCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCategoryRequest.Size(m)
}
func (m *CreateCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCategoryRequest proto.InternalMessageInfo

func (m *CreateCategoryRequest) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *CreateCategoryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCategoryRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type CreateCategoryResponse struct {
	Category             *Category `protobuf:"bytes,1,opt,name=Category,proto3" json:"Category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateCategoryResponse) Reset()         { *m = CreateCategoryResponse{} }
func (m *CreateCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCategoryResponse) ProtoMessage()    {}
func (*CreateCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_943ab93be45729ab, []int{1}
}

func (m *CreateCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCategoryResponse.Unmarshal(m, b)
}
func (m *CreateCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCategoryResponse.Marshal(b, m, deterministic)
}
func (m *CreateCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCategoryResponse.Merge(m, src)
}
func (m *CreateCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCategoryResponse.Size(m)
}
func (m *CreateCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCategoryResponse proto.InternalMessageInfo

func (m *CreateCategoryResponse) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

//------------------------------------------------------------------------------------------------------------------
//  UPDATE
//------------------------------------------------------------------------------------------------------------------
type UpdateCategoryRequest struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=Slug,proto3" json:"Slug,omitempty"`
	ParentId             string   `protobuf:"bytes,2,opt,name=ParentId,proto3" json:"ParentId,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	Path                 string   `protobuf:"bytes,5,opt,name=Path,proto3" json:"Path,omitempty"`
	Status               int32    `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCategoryRequest) Reset()         { *m = UpdateCategoryRequest{} }
func (m *UpdateCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCategoryRequest) ProtoMessage()    {}
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_943ab93be45729ab, []int{2}
}

func (m *UpdateCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCategoryRequest.Unmarshal(m, b)
}
func (m *UpdateCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCategoryRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCategoryRequest.Merge(m, src)
}
func (m *UpdateCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCategoryRequest.Size(m)
}
func (m *UpdateCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCategoryRequest proto.InternalMessageInfo

func (m *UpdateCategoryRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *UpdateCategoryRequest) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *UpdateCategoryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateCategoryRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *UpdateCategoryRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type UpdateCategoryResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCategoryResponse) Reset()         { *m = UpdateCategoryResponse{} }
func (m *UpdateCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCategoryResponse) ProtoMessage()    {}
func (*UpdateCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_943ab93be45729ab, []int{3}
}

func (m *UpdateCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCategoryResponse.Unmarshal(m, b)
}
func (m *UpdateCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCategoryResponse.Marshal(b, m, deterministic)
}
func (m *UpdateCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCategoryResponse.Merge(m, src)
}
func (m *UpdateCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCategoryResponse.Size(m)
}
func (m *UpdateCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCategoryResponse proto.InternalMessageInfo

func (m *UpdateCategoryResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

//------------------------------------------------------------------------------------------------------------------
//  DELETE
//------------------------------------------------------------------------------------------------------------------
type DeleteCategoryRequest struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=Slug,proto3" json:"Slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCategoryRequest) Reset()         { *m = DeleteCategoryRequest{} }
func (m *DeleteCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCategoryRequest) ProtoMessage()    {}
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_943ab93be45729ab, []int{4}
}

func (m *DeleteCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCategoryRequest.Unmarshal(m, b)
}
func (m *DeleteCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCategoryRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCategoryRequest.Merge(m, src)
}
func (m *DeleteCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCategoryRequest.Size(m)
}
func (m *DeleteCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCategoryRequest proto.InternalMessageInfo

func (m *DeleteCategoryRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type DeleteCategoryResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCategoryResponse) Reset()         { *m = DeleteCategoryResponse{} }
func (m *DeleteCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCategoryResponse) ProtoMessage()    {}
func (*DeleteCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_943ab93be45729ab, []int{5}
}

func (m *DeleteCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCategoryResponse.Unmarshal(m, b)
}
func (m *DeleteCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCategoryResponse.Marshal(b, m, deterministic)
}
func (m *DeleteCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCategoryResponse.Merge(m, src)
}
func (m *DeleteCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCategoryResponse.Size(m)
}
func (m *DeleteCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCategoryResponse proto.InternalMessageInfo

func (m *DeleteCategoryResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

//------------------------------------------------------------------------------------------------------------------
//  GET
//------------------------------------------------------------------------------------------------------------------
type GetCategoryRequest struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=Slug,proto3" json:"Slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCategoryRequest) Reset()         { *m = GetCategoryRequest{} }
func (m *GetCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetCategoryRequest) ProtoMessage()    {}
func (*GetCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_943ab93be45729ab, []int{6}
}

func (m *GetCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCategoryRequest.Unmarshal(m, b)
}
func (m *GetCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCategoryRequest.Marshal(b, m, deterministic)
}
func (m *GetCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCategoryRequest.Merge(m, src)
}
func (m *GetCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetCategoryRequest.Size(m)
}
func (m *GetCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCategoryRequest proto.InternalMessageInfo

func (m *GetCategoryRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type GetCategoryResponse struct {
	Category             *Category `protobuf:"bytes,1,opt,name=Category,proto3" json:"Category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetCategoryResponse) Reset()         { *m = GetCategoryResponse{} }
func (m *GetCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetCategoryResponse) ProtoMessage()    {}
func (*GetCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_943ab93be45729ab, []int{7}
}

func (m *GetCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCategoryResponse.Unmarshal(m, b)
}
func (m *GetCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCategoryResponse.Marshal(b, m, deterministic)
}
func (m *GetCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCategoryResponse.Merge(m, src)
}
func (m *GetCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetCategoryResponse.Size(m)
}
func (m *GetCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCategoryResponse proto.InternalMessageInfo

func (m *GetCategoryResponse) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

//------------------------------------------------------------------------------------------------------------------
//  FIND
//------------------------------------------------------------------------------------------------------------------
type FindCategoryRequest struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=Slug,proto3" json:"Slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindCategoryRequest) Reset()         { *m = FindCategoryRequest{} }
func (m *FindCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*FindCategoryRequest) ProtoMessage()    {}
func (*FindCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_943ab93be45729ab, []int{8}
}

func (m *FindCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindCategoryRequest.Unmarshal(m, b)
}
func (m *FindCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindCategoryRequest.Marshal(b, m, deterministic)
}
func (m *FindCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindCategoryRequest.Merge(m, src)
}
func (m *FindCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_FindCategoryRequest.Size(m)
}
func (m *FindCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindCategoryRequest proto.InternalMessageInfo

func (m *FindCategoryRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type FindCategoryResponse struct {
	Categories           []*Category `protobuf:"bytes,1,rep,name=Categories,proto3" json:"Categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FindCategoryResponse) Reset()         { *m = FindCategoryResponse{} }
func (m *FindCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*FindCategoryResponse) ProtoMessage()    {}
func (*FindCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_943ab93be45729ab, []int{9}
}

func (m *FindCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindCategoryResponse.Unmarshal(m, b)
}
func (m *FindCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindCategoryResponse.Marshal(b, m, deterministic)
}
func (m *FindCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindCategoryResponse.Merge(m, src)
}
func (m *FindCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_FindCategoryResponse.Size(m)
}
func (m *FindCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindCategoryResponse proto.InternalMessageInfo

func (m *FindCategoryResponse) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

//------------------------------------------------------------------------------------------------------------------
//  CATEGORY
//------------------------------------------------------------------------------------------------------------------
type Category struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=Slug,proto3" json:"Slug,omitempty"`
	ParentId             string   `protobuf:"bytes,2,opt,name=ParentId,proto3" json:"ParentId,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=Path,proto3" json:"Path,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	Status               int32    `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_943ab93be45729ab, []int{10}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Category) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *Category) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateCategoryRequest)(nil), "protobuf.CreateCategoryRequest")
	proto.RegisterType((*CreateCategoryResponse)(nil), "protobuf.CreateCategoryResponse")
	proto.RegisterType((*UpdateCategoryRequest)(nil), "protobuf.UpdateCategoryRequest")
	proto.RegisterType((*UpdateCategoryResponse)(nil), "protobuf.UpdateCategoryResponse")
	proto.RegisterType((*DeleteCategoryRequest)(nil), "protobuf.DeleteCategoryRequest")
	proto.RegisterType((*DeleteCategoryResponse)(nil), "protobuf.DeleteCategoryResponse")
	proto.RegisterType((*GetCategoryRequest)(nil), "protobuf.GetCategoryRequest")
	proto.RegisterType((*GetCategoryResponse)(nil), "protobuf.GetCategoryResponse")
	proto.RegisterType((*FindCategoryRequest)(nil), "protobuf.FindCategoryRequest")
	proto.RegisterType((*FindCategoryResponse)(nil), "protobuf.FindCategoryResponse")
	proto.RegisterType((*Category)(nil), "protobuf.Category")
}

func init() {
	proto.RegisterFile("services/category/protobuf/category.proto", fileDescriptor_943ab93be45729ab)
}

var fileDescriptor_943ab93be45729ab = []byte{
	// 465 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0x56, 0xda, 0x34, 0x2a, 0xc3, 0x01, 0x34, 0x4b, 0x4b, 0x88, 0x16, 0xb6, 0xf2, 0xa9, 0x0b,
	0x52, 0x03, 0xe5, 0x11, 0x16, 0x58, 0xe0, 0x80, 0x56, 0xad, 0x38, 0x71, 0x40, 0xde, 0x76, 0x28,
	0x91, 0x42, 0x1c, 0x12, 0x67, 0x25, 0x40, 0x5c, 0xb8, 0xf0, 0x00, 0xdc, 0x78, 0x2d, 0x5e, 0x81,
	0x07, 0x41, 0x71, 0xfe, 0x9c, 0xac, 0x23, 0xaa, 0xde, 0xec, 0xf1, 0x37, 0xf3, 0x7d, 0x9e, 0xf9,
	0x06, 0x4e, 0x53, 0x4a, 0xae, 0x82, 0x0d, 0xa5, 0xfe, 0x86, 0x4b, 0xda, 0x89, 0xe4, 0x8b, 0x1f,
	0x27, 0x42, 0x8a, 0xcb, 0xec, 0x43, 0x1d, 0x59, 0xa8, 0x08, 0x8e, 0xab, 0x07, 0xef, 0x78, 0x27,
	0xc4, 0x2e, 0x24, 0x9f, 0xc7, 0x81, 0xcf, 0xa3, 0x48, 0x48, 0x2e, 0x03, 0x11, 0xa5, 0x05, 0x8e,
	0xbd, 0x83, 0xc9, 0x59, 0x42, 0x5c, 0xd2, 0x59, 0x99, 0xbf, 0xa2, 0xcf, 0x19, 0xa5, 0x12, 0x3d,
	0x18, 0x5f, 0xf0, 0x84, 0x22, 0xf9, 0x6a, 0xeb, 0x5a, 0x33, 0x6b, 0x7e, 0x63, 0x55, 0xdf, 0x11,
	0xc1, 0x7e, 0xc3, 0x3f, 0x91, 0x3b, 0x50, 0x71, 0x75, 0xce, 0x63, 0x17, 0x5c, 0x7e, 0x74, 0x87,
	0x45, 0x2c, 0x3f, 0xb3, 0x97, 0x30, 0xed, 0x16, 0x4f, 0x63, 0x11, 0xa5, 0x84, 0x0b, 0x18, 0x57,
	0x31, 0x55, 0xfd, 0xe6, 0x12, 0x17, 0x95, 0xe2, 0x45, 0x8d, 0xae, 0x31, 0xec, 0xa7, 0x05, 0x93,
	0xb7, 0xf1, 0xd6, 0xa0, 0x13, 0xc1, 0x5e, 0x87, 0xd9, 0xae, 0xd4, 0xa8, 0xce, 0x2d, 0xed, 0x83,
	0x1e, 0xed, 0xb6, 0x41, 0xfb, 0xa8, 0xd1, 0x8e, 0x53, 0x70, 0xd6, 0x92, 0xcb, 0x2c, 0x75, 0x9d,
	0x99, 0x35, 0x1f, 0xad, 0xca, 0x1b, 0x7b, 0x0c, 0xd3, 0xae, 0x90, 0xf2, 0x4f, 0x4d, 0x86, 0xd5,
	0xca, 0x78, 0x04, 0x93, 0x67, 0x14, 0xd2, 0x5e, 0xd2, 0xf3, 0xf2, 0x5d, 0xf0, 0x7f, 0xca, 0xcf,
	0x01, 0xcf, 0x49, 0xee, 0x53, 0xfb, 0x39, 0x1c, 0xb5, 0x90, 0x07, 0xce, 0xe2, 0x14, 0x8e, 0x5e,
	0x04, 0xd1, 0x76, 0x1f, 0xc6, 0xd7, 0x70, 0xa7, 0x0d, 0x2d, 0x29, 0x97, 0x00, 0x65, 0x2c, 0xa0,
	0xfc, 0x3f, 0xc3, 0x1e, 0x52, 0x0d, 0xc5, 0xbe, 0x36, 0x32, 0x0f, 0x19, 0x7a, 0xd7, 0x9c, 0x46,
	0x23, 0x34, 0x3d, 0x1e, 0xe9, 0x3d, 0x5e, 0xfe, 0xb6, 0xe1, 0x56, 0x45, 0xbe, 0x2e, 0x76, 0x10,
	0x09, 0x9c, 0xc2, 0xdc, 0x78, 0xa2, 0x29, 0x37, 0xed, 0x92, 0x37, 0xeb, 0x07, 0x14, 0x0d, 0x61,
	0xee, 0x8f, 0x3f, 0x7f, 0x7f, 0x0d, 0x90, 0xdd, 0x56, 0x6b, 0x7a, 0xf5, 0xa4, 0x5e, 0x67, 0x0c,
	0xc1, 0x29, 0xfc, 0xa6, 0xd3, 0x18, 0x57, 0x41, 0xa7, 0x31, 0x5b, 0x94, 0x9d, 0x28, 0x9a, 0x7b,
	0xec, 0x6e, 0x97, 0xc6, 0xff, 0x96, 0xf7, 0xf0, 0x7b, 0xce, 0x56, 0xd8, 0x4f, 0x67, 0x33, 0xba,
	0x57, 0x67, 0x33, 0x3b, 0xb6, 0x62, 0x7b, 0xd8, 0xcb, 0xb6, 0x81, 0xe1, 0x39, 0x49, 0x3c, 0x6e,
	0x2a, 0x5d, 0x77, 0xb2, 0x77, 0xbf, 0xe7, 0xb5, 0x4d, 0x82, 0xbd, 0x24, 0xef, 0xc1, 0xce, 0x3d,
	0x88, 0x5a, 0x1d, 0x83, 0x7d, 0xbd, 0x07, 0x7d, 0xcf, 0xed, 0x09, 0xe1, 0xb5, 0x09, 0x5d, 0x3a,
	0x2a, 0xf1, 0xe9, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x72, 0xc6, 0xb9, 0x32, 0x9e, 0x05, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CategoryServiceClient is the client API for CategoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CategoryServiceClient interface {
	//Создание записи
	Create(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error)
	//Обновление записи
	Update(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error)
	//Удаление записи
	Delete(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error)
	//Возвращает запись по SLUG
	Get(ctx context.Context, in *GetCategoryRequest, opts ...grpc.CallOption) (*GetCategoryResponse, error)
	//Писк
	Find(ctx context.Context, in *FindCategoryRequest, opts ...grpc.CallOption) (*FindCategoryResponse, error)
}

type categoryServiceClient struct {
	cc *grpc.ClientConn
}

func NewCategoryServiceClient(cc *grpc.ClientConn) CategoryServiceClient {
	return &categoryServiceClient{cc}
}

func (c *categoryServiceClient) Create(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error) {
	out := new(CreateCategoryResponse)
	err := c.cc.Invoke(ctx, "/protobuf.CategoryService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryServiceClient) Update(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error) {
	out := new(UpdateCategoryResponse)
	err := c.cc.Invoke(ctx, "/protobuf.CategoryService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryServiceClient) Delete(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error) {
	out := new(DeleteCategoryResponse)
	err := c.cc.Invoke(ctx, "/protobuf.CategoryService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryServiceClient) Get(ctx context.Context, in *GetCategoryRequest, opts ...grpc.CallOption) (*GetCategoryResponse, error) {
	out := new(GetCategoryResponse)
	err := c.cc.Invoke(ctx, "/protobuf.CategoryService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryServiceClient) Find(ctx context.Context, in *FindCategoryRequest, opts ...grpc.CallOption) (*FindCategoryResponse, error) {
	out := new(FindCategoryResponse)
	err := c.cc.Invoke(ctx, "/protobuf.CategoryService/Find", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategoryServiceServer is the server API for CategoryService service.
type CategoryServiceServer interface {
	//Создание записи
	Create(context.Context, *CreateCategoryRequest) (*CreateCategoryResponse, error)
	//Обновление записи
	Update(context.Context, *UpdateCategoryRequest) (*UpdateCategoryResponse, error)
	//Удаление записи
	Delete(context.Context, *DeleteCategoryRequest) (*DeleteCategoryResponse, error)
	//Возвращает запись по SLUG
	Get(context.Context, *GetCategoryRequest) (*GetCategoryResponse, error)
	//Писк
	Find(context.Context, *FindCategoryRequest) (*FindCategoryResponse, error)
}

// UnimplementedCategoryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCategoryServiceServer struct {
}

func (*UnimplementedCategoryServiceServer) Create(ctx context.Context, req *CreateCategoryRequest) (*CreateCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedCategoryServiceServer) Update(ctx context.Context, req *UpdateCategoryRequest) (*UpdateCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedCategoryServiceServer) Delete(ctx context.Context, req *DeleteCategoryRequest) (*DeleteCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedCategoryServiceServer) Get(ctx context.Context, req *GetCategoryRequest) (*GetCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedCategoryServiceServer) Find(ctx context.Context, req *FindCategoryRequest) (*FindCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}

func RegisterCategoryServiceServer(s *grpc.Server, srv CategoryServiceServer) {
	s.RegisterService(&_CategoryService_serviceDesc, srv)
}

func _CategoryService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.CategoryService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServiceServer).Create(ctx, req.(*CreateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.CategoryService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServiceServer).Update(ctx, req.(*UpdateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.CategoryService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServiceServer).Delete(ctx, req.(*DeleteCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.CategoryService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServiceServer).Get(ctx, req.(*GetCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.CategoryService/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServiceServer).Find(ctx, req.(*FindCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CategoryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.CategoryService",
	HandlerType: (*CategoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CategoryService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CategoryService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CategoryService_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _CategoryService_Get_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _CategoryService_Find_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/category/protobuf/category.proto",
}
