// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/post/protobuf/post.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//------------------------------------------------------------------------------------------------------------------
//  CREATE
//------------------------------------------------------------------------------------------------------------------
type CreatePostRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	SubTitle             string   `protobuf:"bytes,2,opt,name=SubTitle,proto3" json:"SubTitle,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	Categories           string   `protobuf:"bytes,4,opt,name=Categories,proto3" json:"Categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostRequest) Reset()         { *m = CreatePostRequest{} }
func (m *CreatePostRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostRequest) ProtoMessage()    {}
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_873ce1b67c5815b1, []int{0}
}

func (m *CreatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostRequest.Unmarshal(m, b)
}
func (m *CreatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostRequest.Marshal(b, m, deterministic)
}
func (m *CreatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostRequest.Merge(m, src)
}
func (m *CreatePostRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostRequest.Size(m)
}
func (m *CreatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostRequest proto.InternalMessageInfo

func (m *CreatePostRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreatePostRequest) GetSubTitle() string {
	if m != nil {
		return m.SubTitle
	}
	return ""
}

func (m *CreatePostRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CreatePostRequest) GetCategories() string {
	if m != nil {
		return m.Categories
	}
	return ""
}

type CreatePostResponse struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=Post,proto3" json:"Post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostResponse) Reset()         { *m = CreatePostResponse{} }
func (m *CreatePostResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePostResponse) ProtoMessage()    {}
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_873ce1b67c5815b1, []int{1}
}

func (m *CreatePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostResponse.Unmarshal(m, b)
}
func (m *CreatePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostResponse.Marshal(b, m, deterministic)
}
func (m *CreatePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostResponse.Merge(m, src)
}
func (m *CreatePostResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePostResponse.Size(m)
}
func (m *CreatePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostResponse proto.InternalMessageInfo

func (m *CreatePostResponse) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

//------------------------------------------------------------------------------------------------------------------
//  UPDATE
//------------------------------------------------------------------------------------------------------------------
type UpdatePostRequest struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=Slug,proto3" json:"Slug,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	SubTitle             string   `protobuf:"bytes,3,opt,name=SubTitle,proto3" json:"SubTitle,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`
	Status               int32    `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`
	Categories           string   `protobuf:"bytes,6,opt,name=Categories,proto3" json:"Categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePostRequest) Reset()         { *m = UpdatePostRequest{} }
func (m *UpdatePostRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePostRequest) ProtoMessage()    {}
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_873ce1b67c5815b1, []int{2}
}

func (m *UpdatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostRequest.Unmarshal(m, b)
}
func (m *UpdatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostRequest.Merge(m, src)
}
func (m *UpdatePostRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePostRequest.Size(m)
}
func (m *UpdatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostRequest proto.InternalMessageInfo

func (m *UpdatePostRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *UpdatePostRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdatePostRequest) GetSubTitle() string {
	if m != nil {
		return m.SubTitle
	}
	return ""
}

func (m *UpdatePostRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *UpdatePostRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdatePostRequest) GetCategories() string {
	if m != nil {
		return m.Categories
	}
	return ""
}

type UpdatePostResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePostResponse) Reset()         { *m = UpdatePostResponse{} }
func (m *UpdatePostResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePostResponse) ProtoMessage()    {}
func (*UpdatePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_873ce1b67c5815b1, []int{3}
}

func (m *UpdatePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostResponse.Unmarshal(m, b)
}
func (m *UpdatePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostResponse.Merge(m, src)
}
func (m *UpdatePostResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePostResponse.Size(m)
}
func (m *UpdatePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostResponse proto.InternalMessageInfo

func (m *UpdatePostResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

//------------------------------------------------------------------------------------------------------------------
//  DELETE
//------------------------------------------------------------------------------------------------------------------
type DeletePostRequest struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=Slug,proto3" json:"Slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePostRequest) Reset()         { *m = DeletePostRequest{} }
func (m *DeletePostRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePostRequest) ProtoMessage()    {}
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_873ce1b67c5815b1, []int{4}
}

func (m *DeletePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePostRequest.Unmarshal(m, b)
}
func (m *DeletePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePostRequest.Marshal(b, m, deterministic)
}
func (m *DeletePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePostRequest.Merge(m, src)
}
func (m *DeletePostRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePostRequest.Size(m)
}
func (m *DeletePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePostRequest proto.InternalMessageInfo

func (m *DeletePostRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type DeletePostResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePostResponse) Reset()         { *m = DeletePostResponse{} }
func (m *DeletePostResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePostResponse) ProtoMessage()    {}
func (*DeletePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_873ce1b67c5815b1, []int{5}
}

func (m *DeletePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePostResponse.Unmarshal(m, b)
}
func (m *DeletePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePostResponse.Marshal(b, m, deterministic)
}
func (m *DeletePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePostResponse.Merge(m, src)
}
func (m *DeletePostResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePostResponse.Size(m)
}
func (m *DeletePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePostResponse proto.InternalMessageInfo

func (m *DeletePostResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

//------------------------------------------------------------------------------------------------------------------
//  GET
//------------------------------------------------------------------------------------------------------------------
type GetPostRequest struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=Slug,proto3" json:"Slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostRequest) Reset()         { *m = GetPostRequest{} }
func (m *GetPostRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostRequest) ProtoMessage()    {}
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_873ce1b67c5815b1, []int{6}
}

func (m *GetPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostRequest.Unmarshal(m, b)
}
func (m *GetPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostRequest.Marshal(b, m, deterministic)
}
func (m *GetPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostRequest.Merge(m, src)
}
func (m *GetPostRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostRequest.Size(m)
}
func (m *GetPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostRequest proto.InternalMessageInfo

func (m *GetPostRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type GetPostResponse struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=Post,proto3" json:"Post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostResponse) Reset()         { *m = GetPostResponse{} }
func (m *GetPostResponse) String() string { return proto.CompactTextString(m) }
func (*GetPostResponse) ProtoMessage()    {}
func (*GetPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_873ce1b67c5815b1, []int{7}
}

func (m *GetPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostResponse.Unmarshal(m, b)
}
func (m *GetPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostResponse.Marshal(b, m, deterministic)
}
func (m *GetPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostResponse.Merge(m, src)
}
func (m *GetPostResponse) XXX_Size() int {
	return xxx_messageInfo_GetPostResponse.Size(m)
}
func (m *GetPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostResponse proto.InternalMessageInfo

func (m *GetPostResponse) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

//------------------------------------------------------------------------------------------------------------------
//  FIND POST
//------------------------------------------------------------------------------------------------------------------
type FindPostRequest struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=Slug,proto3" json:"Slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindPostRequest) Reset()         { *m = FindPostRequest{} }
func (m *FindPostRequest) String() string { return proto.CompactTextString(m) }
func (*FindPostRequest) ProtoMessage()    {}
func (*FindPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_873ce1b67c5815b1, []int{8}
}

func (m *FindPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindPostRequest.Unmarshal(m, b)
}
func (m *FindPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindPostRequest.Marshal(b, m, deterministic)
}
func (m *FindPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindPostRequest.Merge(m, src)
}
func (m *FindPostRequest) XXX_Size() int {
	return xxx_messageInfo_FindPostRequest.Size(m)
}
func (m *FindPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindPostRequest proto.InternalMessageInfo

func (m *FindPostRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type FindPostResponse struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=Posts,proto3" json:"Posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindPostResponse) Reset()         { *m = FindPostResponse{} }
func (m *FindPostResponse) String() string { return proto.CompactTextString(m) }
func (*FindPostResponse) ProtoMessage()    {}
func (*FindPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_873ce1b67c5815b1, []int{9}
}

func (m *FindPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindPostResponse.Unmarshal(m, b)
}
func (m *FindPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindPostResponse.Marshal(b, m, deterministic)
}
func (m *FindPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindPostResponse.Merge(m, src)
}
func (m *FindPostResponse) XXX_Size() int {
	return xxx_messageInfo_FindPostResponse.Size(m)
}
func (m *FindPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindPostResponse proto.InternalMessageInfo

func (m *FindPostResponse) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

//------------------------------------------------------------------------------------------------------------------
//  GET AUTHOR
//------------------------------------------------------------------------------------------------------------------
type GetAuthorRequest struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=Slug,proto3" json:"Slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuthorRequest) Reset()         { *m = GetAuthorRequest{} }
func (m *GetAuthorRequest) String() string { return proto.CompactTextString(m) }
func (*GetAuthorRequest) ProtoMessage()    {}
func (*GetAuthorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_873ce1b67c5815b1, []int{10}
}

func (m *GetAuthorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthorRequest.Unmarshal(m, b)
}
func (m *GetAuthorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthorRequest.Marshal(b, m, deterministic)
}
func (m *GetAuthorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthorRequest.Merge(m, src)
}
func (m *GetAuthorRequest) XXX_Size() int {
	return xxx_messageInfo_GetAuthorRequest.Size(m)
}
func (m *GetAuthorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthorRequest proto.InternalMessageInfo

func (m *GetAuthorRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type GetAuthorResponse struct {
	Author               *Author  `protobuf:"bytes,1,opt,name=Author,proto3" json:"Author,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuthorResponse) Reset()         { *m = GetAuthorResponse{} }
func (m *GetAuthorResponse) String() string { return proto.CompactTextString(m) }
func (*GetAuthorResponse) ProtoMessage()    {}
func (*GetAuthorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_873ce1b67c5815b1, []int{11}
}

func (m *GetAuthorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthorResponse.Unmarshal(m, b)
}
func (m *GetAuthorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthorResponse.Marshal(b, m, deterministic)
}
func (m *GetAuthorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthorResponse.Merge(m, src)
}
func (m *GetAuthorResponse) XXX_Size() int {
	return xxx_messageInfo_GetAuthorResponse.Size(m)
}
func (m *GetAuthorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthorResponse proto.InternalMessageInfo

func (m *GetAuthorResponse) GetAuthor() *Author {
	if m != nil {
		return m.Author
	}
	return nil
}

//------------------------------------------------------------------------------------------------------------------
//  FIND AUTHOR
//------------------------------------------------------------------------------------------------------------------
type FindAuthorRequest struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=Slug,proto3" json:"Slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAuthorRequest) Reset()         { *m = FindAuthorRequest{} }
func (m *FindAuthorRequest) String() string { return proto.CompactTextString(m) }
func (*FindAuthorRequest) ProtoMessage()    {}
func (*FindAuthorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_873ce1b67c5815b1, []int{12}
}

func (m *FindAuthorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAuthorRequest.Unmarshal(m, b)
}
func (m *FindAuthorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAuthorRequest.Marshal(b, m, deterministic)
}
func (m *FindAuthorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAuthorRequest.Merge(m, src)
}
func (m *FindAuthorRequest) XXX_Size() int {
	return xxx_messageInfo_FindAuthorRequest.Size(m)
}
func (m *FindAuthorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAuthorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindAuthorRequest proto.InternalMessageInfo

func (m *FindAuthorRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type FindAuthorResponse struct {
	Authors              []*Author `protobuf:"bytes,1,rep,name=Authors,proto3" json:"Authors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FindAuthorResponse) Reset()         { *m = FindAuthorResponse{} }
func (m *FindAuthorResponse) String() string { return proto.CompactTextString(m) }
func (*FindAuthorResponse) ProtoMessage()    {}
func (*FindAuthorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_873ce1b67c5815b1, []int{13}
}

func (m *FindAuthorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAuthorResponse.Unmarshal(m, b)
}
func (m *FindAuthorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAuthorResponse.Marshal(b, m, deterministic)
}
func (m *FindAuthorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAuthorResponse.Merge(m, src)
}
func (m *FindAuthorResponse) XXX_Size() int {
	return xxx_messageInfo_FindAuthorResponse.Size(m)
}
func (m *FindAuthorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAuthorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindAuthorResponse proto.InternalMessageInfo

func (m *FindAuthorResponse) GetAuthors() []*Author {
	if m != nil {
		return m.Authors
	}
	return nil
}

//------------------------------------------------------------------------------------------------------------------
//  GET CATEGORY
//------------------------------------------------------------------------------------------------------------------
type GetPostCategoryRequest struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=Slug,proto3" json:"Slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostCategoryRequest) Reset()         { *m = GetPostCategoryRequest{} }
func (m *GetPostCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostCategoryRequest) ProtoMessage()    {}
func (*GetPostCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_873ce1b67c5815b1, []int{14}
}

func (m *GetPostCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostCategoryRequest.Unmarshal(m, b)
}
func (m *GetPostCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostCategoryRequest.Marshal(b, m, deterministic)
}
func (m *GetPostCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostCategoryRequest.Merge(m, src)
}
func (m *GetPostCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostCategoryRequest.Size(m)
}
func (m *GetPostCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostCategoryRequest proto.InternalMessageInfo

func (m *GetPostCategoryRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type GetPostCategoryResponse struct {
	Category             *PostCategory `protobuf:"bytes,1,opt,name=Category,proto3" json:"Category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetPostCategoryResponse) Reset()         { *m = GetPostCategoryResponse{} }
func (m *GetPostCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetPostCategoryResponse) ProtoMessage()    {}
func (*GetPostCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_873ce1b67c5815b1, []int{15}
}

func (m *GetPostCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostCategoryResponse.Unmarshal(m, b)
}
func (m *GetPostCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostCategoryResponse.Marshal(b, m, deterministic)
}
func (m *GetPostCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostCategoryResponse.Merge(m, src)
}
func (m *GetPostCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetPostCategoryResponse.Size(m)
}
func (m *GetPostCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostCategoryResponse proto.InternalMessageInfo

func (m *GetPostCategoryResponse) GetCategory() *PostCategory {
	if m != nil {
		return m.Category
	}
	return nil
}

//------------------------------------------------------------------------------------------------------------------
//  POST
//------------------------------------------------------------------------------------------------------------------
type Post struct {
	Slug                 string          `protobuf:"bytes,1,opt,name=Slug,proto3" json:"Slug,omitempty"`
	Title                string          `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	SubTitle             string          `protobuf:"bytes,3,opt,name=SubTitle,proto3" json:"SubTitle,omitempty"`
	Content              string          `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`
	UserId               string          `protobuf:"bytes,5,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Status               int32           `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty"`
	Src                  string          `protobuf:"bytes,7,opt,name=Src,proto3" json:"Src,omitempty"`
	Author               *Author         `protobuf:"bytes,8,opt,name=Author,proto3" json:"Author,omitempty"`
	Categories           string          `protobuf:"bytes,9,opt,name=Categories,proto3" json:"Categories,omitempty"`
	PostCategories       []*PostCategory `protobuf:"bytes,10,rep,name=PostCategories,proto3" json:"PostCategories,omitempty"`
	Comments             string          `protobuf:"bytes,11,opt,name=Comments,proto3" json:"Comments,omitempty"`
	PostComments         []*PostComment  `protobuf:"bytes,12,rep,name=PostComments,proto3" json:"PostComments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_873ce1b67c5815b1, []int{16}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetSubTitle() string {
	if m != nil {
		return m.SubTitle
	}
	return ""
}

func (m *Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Post) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Post) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Post) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

func (m *Post) GetAuthor() *Author {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Post) GetCategories() string {
	if m != nil {
		return m.Categories
	}
	return ""
}

func (m *Post) GetPostCategories() []*PostCategory {
	if m != nil {
		return m.PostCategories
	}
	return nil
}

func (m *Post) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

func (m *Post) GetPostComments() []*PostComment {
	if m != nil {
		return m.PostComments
	}
	return nil
}

//------------------------------------------------------------------------------------------------------------------
//  Author
//------------------------------------------------------------------------------------------------------------------
type Author struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=Slug,proto3" json:"Slug,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=LastName,proto3" json:"LastName,omitempty"`
	SrcAvatar            string   `protobuf:"bytes,4,opt,name=SrcAvatar,proto3" json:"SrcAvatar,omitempty"`
	SrcCover             string   `protobuf:"bytes,5,opt,name=SrcCover,proto3" json:"SrcCover,omitempty"`
	Posts                []*Post  `protobuf:"bytes,6,rep,name=Posts,proto3" json:"Posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Author) Reset()         { *m = Author{} }
func (m *Author) String() string { return proto.CompactTextString(m) }
func (*Author) ProtoMessage()    {}
func (*Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_873ce1b67c5815b1, []int{17}
}

func (m *Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Author.Unmarshal(m, b)
}
func (m *Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Author.Marshal(b, m, deterministic)
}
func (m *Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Author.Merge(m, src)
}
func (m *Author) XXX_Size() int {
	return xxx_messageInfo_Author.Size(m)
}
func (m *Author) XXX_DiscardUnknown() {
	xxx_messageInfo_Author.DiscardUnknown(m)
}

var xxx_messageInfo_Author proto.InternalMessageInfo

func (m *Author) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Author) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Author) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Author) GetSrcAvatar() string {
	if m != nil {
		return m.SrcAvatar
	}
	return ""
}

func (m *Author) GetSrcCover() string {
	if m != nil {
		return m.SrcCover
	}
	return ""
}

func (m *Author) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

//------------------------------------------------------------------------------------------------------------------
//  PostCategory
//------------------------------------------------------------------------------------------------------------------
type PostCategory struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=Slug,proto3" json:"Slug,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Posts                []*Post  `protobuf:"bytes,3,rep,name=Posts,proto3" json:"Posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostCategory) Reset()         { *m = PostCategory{} }
func (m *PostCategory) String() string { return proto.CompactTextString(m) }
func (*PostCategory) ProtoMessage()    {}
func (*PostCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_873ce1b67c5815b1, []int{18}
}

func (m *PostCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostCategory.Unmarshal(m, b)
}
func (m *PostCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostCategory.Marshal(b, m, deterministic)
}
func (m *PostCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostCategory.Merge(m, src)
}
func (m *PostCategory) XXX_Size() int {
	return xxx_messageInfo_PostCategory.Size(m)
}
func (m *PostCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_PostCategory.DiscardUnknown(m)
}

var xxx_messageInfo_PostCategory proto.InternalMessageInfo

func (m *PostCategory) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *PostCategory) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PostCategory) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

//------------------------------------------------------------------------------------------------------------------
//  PostComment
//------------------------------------------------------------------------------------------------------------------
type PostComment struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=Slug,proto3" json:"Slug,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	Author               *Author  `protobuf:"bytes,3,opt,name=Author,proto3" json:"Author,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostComment) Reset()         { *m = PostComment{} }
func (m *PostComment) String() string { return proto.CompactTextString(m) }
func (*PostComment) ProtoMessage()    {}
func (*PostComment) Descriptor() ([]byte, []int) {
	return fileDescriptor_873ce1b67c5815b1, []int{19}
}

func (m *PostComment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostComment.Unmarshal(m, b)
}
func (m *PostComment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostComment.Marshal(b, m, deterministic)
}
func (m *PostComment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostComment.Merge(m, src)
}
func (m *PostComment) XXX_Size() int {
	return xxx_messageInfo_PostComment.Size(m)
}
func (m *PostComment) XXX_DiscardUnknown() {
	xxx_messageInfo_PostComment.DiscardUnknown(m)
}

var xxx_messageInfo_PostComment proto.InternalMessageInfo

func (m *PostComment) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *PostComment) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PostComment) GetAuthor() *Author {
	if m != nil {
		return m.Author
	}
	return nil
}

func init() {
	proto.RegisterType((*CreatePostRequest)(nil), "protobuf.CreatePostRequest")
	proto.RegisterType((*CreatePostResponse)(nil), "protobuf.CreatePostResponse")
	proto.RegisterType((*UpdatePostRequest)(nil), "protobuf.UpdatePostRequest")
	proto.RegisterType((*UpdatePostResponse)(nil), "protobuf.UpdatePostResponse")
	proto.RegisterType((*DeletePostRequest)(nil), "protobuf.DeletePostRequest")
	proto.RegisterType((*DeletePostResponse)(nil), "protobuf.DeletePostResponse")
	proto.RegisterType((*GetPostRequest)(nil), "protobuf.GetPostRequest")
	proto.RegisterType((*GetPostResponse)(nil), "protobuf.GetPostResponse")
	proto.RegisterType((*FindPostRequest)(nil), "protobuf.FindPostRequest")
	proto.RegisterType((*FindPostResponse)(nil), "protobuf.FindPostResponse")
	proto.RegisterType((*GetAuthorRequest)(nil), "protobuf.GetAuthorRequest")
	proto.RegisterType((*GetAuthorResponse)(nil), "protobuf.GetAuthorResponse")
	proto.RegisterType((*FindAuthorRequest)(nil), "protobuf.FindAuthorRequest")
	proto.RegisterType((*FindAuthorResponse)(nil), "protobuf.FindAuthorResponse")
	proto.RegisterType((*GetPostCategoryRequest)(nil), "protobuf.GetPostCategoryRequest")
	proto.RegisterType((*GetPostCategoryResponse)(nil), "protobuf.GetPostCategoryResponse")
	proto.RegisterType((*Post)(nil), "protobuf.Post")
	proto.RegisterType((*Author)(nil), "protobuf.Author")
	proto.RegisterType((*PostCategory)(nil), "protobuf.PostCategory")
	proto.RegisterType((*PostComment)(nil), "protobuf.PostComment")
}

func init() { proto.RegisterFile("services/post/protobuf/post.proto", fileDescriptor_873ce1b67c5815b1) }

var fileDescriptor_873ce1b67c5815b1 = []byte{
	// 817 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xdd, 0x6a, 0x13, 0x4d,
	0x18, 0x26, 0xd9, 0x64, 0x9b, 0xbc, 0x29, 0x69, 0x32, 0x5f, 0x9b, 0x6e, 0xb7, 0xf9, 0x4a, 0xbb,
	0xf4, 0xfb, 0x2c, 0xa5, 0x34, 0x58, 0x11, 0xea, 0x81, 0x62, 0x89, 0xb4, 0x08, 0x2a, 0x92, 0x58,
	0x44, 0xf0, 0xc0, 0x6d, 0x3a, 0xc6, 0x40, 0xba, 0x1b, 0x77, 0x26, 0x01, 0x51, 0x11, 0x3c, 0xf3,
	0xd8, 0x0b, 0xf0, 0x02, 0x3c, 0xf7, 0x46, 0xbc, 0x05, 0x2f, 0x44, 0xe6, 0x6f, 0x67, 0x36, 0xbb,
	0xdd, 0xe0, 0x89, 0x67, 0x79, 0xe7, 0x7d, 0xf6, 0x79, 0xde, 0x9f, 0x99, 0x3c, 0xb0, 0x43, 0x70,
	0x34, 0x1b, 0x0d, 0x30, 0xe9, 0x4c, 0x42, 0x42, 0x3b, 0x93, 0x28, 0xa4, 0xe1, 0xc5, 0xf4, 0x35,
	0x8f, 0x0e, 0x79, 0x84, 0x2a, 0xea, 0xd0, 0x6d, 0x0f, 0xc3, 0x70, 0x38, 0xc6, 0x1d, 0x7f, 0x32,
	0xea, 0xf8, 0x41, 0x10, 0x52, 0x9f, 0x8e, 0xc2, 0x80, 0x08, 0x9c, 0xf7, 0x09, 0x9a, 0xdd, 0x08,
	0xfb, 0x14, 0x3f, 0x0d, 0x09, 0xed, 0xe1, 0xb7, 0x53, 0x4c, 0x28, 0x5a, 0x85, 0xf2, 0xb3, 0x11,
	0x1d, 0x63, 0xa7, 0xb0, 0x5d, 0xd8, 0xab, 0xf6, 0x44, 0x80, 0x5c, 0xa8, 0xf4, 0xa7, 0x17, 0x22,
	0x51, 0xe4, 0x89, 0x38, 0x46, 0x0e, 0x2c, 0x75, 0xc3, 0x80, 0xe2, 0x80, 0x3a, 0x16, 0x4f, 0xa9,
	0x10, 0x6d, 0x01, 0x74, 0x7d, 0x8a, 0x87, 0x61, 0x34, 0xc2, 0xc4, 0x29, 0xf1, 0xa4, 0x71, 0xe2,
	0x1d, 0x03, 0x32, 0x0b, 0x20, 0x93, 0x30, 0x20, 0x18, 0x79, 0x50, 0x62, 0x31, 0x2f, 0xa0, 0x76,
	0x54, 0x3f, 0x54, 0xdd, 0x1c, 0x72, 0x14, 0xcf, 0x79, 0xdf, 0x0b, 0xd0, 0x3c, 0x9f, 0x5c, 0xce,
	0xd5, 0x8e, 0xa0, 0xd4, 0x1f, 0x4f, 0x87, 0xb2, 0x74, 0xfe, 0x5b, 0xf7, 0x53, 0xbc, 0xae, 0x1f,
	0xeb, 0xfa, 0x7e, 0x4a, 0xc9, 0x7e, 0x5a, 0x60, 0xf7, 0xa9, 0x4f, 0xa7, 0xc4, 0x29, 0x6f, 0x17,
	0xf6, 0xca, 0x3d, 0x19, 0xcd, 0xf5, 0x69, 0xa7, 0xfa, 0x3c, 0x00, 0x64, 0x16, 0x2b, 0xfb, 0xd4,
	0x6c, 0x05, 0x93, 0xcd, 0xbb, 0x01, 0xcd, 0x07, 0x78, 0x8c, 0x17, 0xb6, 0xc6, 0x68, 0x4d, 0xe0,
	0x02, 0xda, 0x5d, 0xa8, 0x9f, 0x61, 0xba, 0x88, 0xf3, 0x36, 0xac, 0xc4, 0xa8, 0x3f, 0xd8, 0xc7,
	0x7f, 0xb0, 0x72, 0x3a, 0x0a, 0x2e, 0x17, 0xb1, 0x1f, 0x43, 0x43, 0xc3, 0x24, 0xfd, 0x2e, 0x94,
	0x59, 0xcc, 0xca, 0xb5, 0x32, 0xf8, 0x45, 0xd2, 0xfb, 0x1f, 0x1a, 0x67, 0x98, 0x9e, 0x4c, 0xe9,
	0x9b, 0x30, 0xca, 0x53, 0xb8, 0x0b, 0x4d, 0x03, 0x27, 0x25, 0xf6, 0xc0, 0x16, 0x27, 0xb2, 0x87,
	0x86, 0xd6, 0x90, 0x48, 0x99, 0x67, 0xb3, 0x67, 0x05, 0x2e, 0xd6, 0xb9, 0x0f, 0xc8, 0x04, 0x4a,
	0xa1, 0x7d, 0x58, 0x12, 0x27, 0xaa, 0x9b, 0xb4, 0x92, 0x02, 0x78, 0x07, 0xd0, 0x92, 0x93, 0x96,
	0x37, 0xe5, 0x5d, 0x9e, 0xde, 0x63, 0x58, 0x4f, 0xa1, 0xa5, 0xe8, 0x11, 0x54, 0xd4, 0x99, 0xec,
	0xaf, 0x95, 0x9c, 0x61, 0xfc, 0x45, 0x8c, 0xf3, 0xbe, 0x58, 0x62, 0xa9, 0x7f, 0xe3, 0xc9, 0x9c,
	0x13, 0x1c, 0x3d, 0xbc, 0xe4, 0x4f, 0xa6, 0xda, 0x93, 0x91, 0x71, 0x4b, 0xed, 0xc4, 0x53, 0x6a,
	0x80, 0xd5, 0x8f, 0x06, 0xce, 0x12, 0x07, 0xb3, 0x9f, 0xc6, 0xf2, 0x2a, 0xf9, 0xcb, 0x9b, 0x7b,
	0x86, 0xd5, 0xf9, 0x67, 0x88, 0xee, 0x41, 0xdd, 0x18, 0x07, 0xc3, 0x00, 0x5f, 0xd2, 0x75, 0xe3,
	0x9a, 0x43, 0xb3, 0x09, 0x74, 0xc3, 0xab, 0x2b, 0x1c, 0x50, 0xe2, 0xd4, 0xc4, 0x04, 0x54, 0x8c,
	0xee, 0xc0, 0x32, 0x47, 0xab, 0xfc, 0x32, 0x67, 0x5e, 0x9b, 0x63, 0x16, 0xd9, 0x5e, 0x02, 0xea,
	0xfd, 0x28, 0xa8, 0x0e, 0x33, 0xb7, 0xd1, 0x86, 0xea, 0xe9, 0x28, 0x22, 0xf4, 0x89, 0x7f, 0xa5,
	0x36, 0xa2, 0x0f, 0x58, 0x4d, 0x8f, 0x7c, 0x99, 0x94, 0x5b, 0x51, 0x31, 0xfb, 0xb2, 0x1f, 0x0d,
	0x4e, 0x66, 0x3e, 0xf5, 0x23, 0xb9, 0x17, 0x7d, 0xc0, 0xf7, 0x19, 0x0d, 0xba, 0xe1, 0x0c, 0x47,
	0x72, 0x37, 0x71, 0xac, 0xdf, 0xa4, 0x9d, 0xf7, 0x26, 0x5f, 0xca, 0x9e, 0xe5, 0xbc, 0x32, 0xab,
	0x47, 0x50, 0x32, 0x0a, 0xe7, 0xbf, 0x35, 0xbb, 0x95, 0xc7, 0x8e, 0xa1, 0x66, 0x8c, 0x29, 0x93,
	0xdc, 0xb8, 0x76, 0xc5, 0xe4, 0xb5, 0xd3, 0x97, 0xc6, 0xca, 0xbf, 0x34, 0x47, 0xdf, 0x6c, 0xa1,
	0xd3, 0x17, 0xb6, 0x8a, 0x5e, 0x80, 0x2d, 0x3c, 0x09, 0x6d, 0xea, 0x6f, 0x52, 0x36, 0xe9, 0xb6,
	0xb3, 0x93, 0xe2, 0x49, 0x7a, 0xab, 0x9f, 0x7f, 0xfe, 0xfa, 0x5a, 0xac, 0x7b, 0xcb, 0xdc, 0x79,
	0x67, 0x37, 0xb9, 0x3b, 0xa3, 0x57, 0x60, 0x0b, 0x1b, 0x30, 0xa9, 0x53, 0x2e, 0x66, 0x52, 0xa7,
	0x5d, 0xc3, 0xdb, 0xe4, 0xd4, 0x6b, 0xde, 0x3f, 0x26, 0x75, 0xe7, 0x3d, 0x9b, 0xc7, 0x47, 0xa6,
	0x20, 0x1c, 0xc1, 0x54, 0x48, 0x99, 0x89, 0xa9, 0x90, 0x36, 0x10, 0xa5, 0xb0, 0x9f, 0xa9, 0xf0,
	0x21, 0xf6, 0x87, 0x78, 0xed, 0xdb, 0x9a, 0x2d, 0xfb, 0x0f, 0xcd, 0xdd, 0xc9, 0x41, 0x48, 0xd1,
	0x5d, 0x2e, 0xba, 0x85, 0xda, 0x09, 0xd1, 0x81, 0x84, 0x29, 0xf5, 0x3e, 0x94, 0xd8, 0xbf, 0x2e,
	0xda, 0xd0, 0x84, 0x73, 0xb6, 0xe3, 0xba, 0x59, 0xa9, 0xe4, 0x5a, 0x50, 0x72, 0x2d, 0xcf, 0xc1,
	0x3a, 0xc3, 0x14, 0x39, 0xa9, 0x22, 0x15, 0xe5, 0x46, 0x46, 0x26, 0x39, 0x2b, 0x94, 0x39, 0xab,
	0x01, 0x54, 0x63, 0x2f, 0x42, 0x6e, 0x82, 0x24, 0x61, 0x30, 0xee, 0x66, 0x66, 0x4e, 0x4a, 0xfc,
	0xcb, 0x25, 0xd6, 0xd1, 0x9a, 0x92, 0xf0, 0x79, 0x5e, 0xaf, 0xbc, 0xa6, 0x8d, 0x88, 0x98, 0x7b,
	0x4f, 0x19, 0x99, 0xb9, 0xf7, 0xb4, 0x79, 0x79, 0x2d, 0x2e, 0xd4, 0x40, 0xf5, 0xa4, 0xd0, 0x85,
	0xcd, 0x3f, 0xba, 0xf5, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x25, 0xe1, 0xaf, 0xb2, 0x7a, 0x0a, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostServiceClient is the client API for PostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostServiceClient interface {
	//Создание записи
	Create(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error)
	//Обновление записи
	Update(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error)
	//Удаление записи
	Delete(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error)
	//Информация о категории и связанных постах
	GetPostCategory(ctx context.Context, in *GetPostCategoryRequest, opts ...grpc.CallOption) (*GetPostCategoryResponse, error)
	//Список всех постов
	Find(ctx context.Context, in *FindPostRequest, opts ...grpc.CallOption) (*FindPostResponse, error)
	//Возвращает запись по SLUG
	Get(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostResponse, error)
	//Информация о авторе
	GetAuthor(ctx context.Context, in *GetAuthorRequest, opts ...grpc.CallOption) (*GetAuthorResponse, error)
	//Список всех авторов
	FindAuthors(ctx context.Context, in *FindAuthorRequest, opts ...grpc.CallOption) (*FindAuthorResponse, error)
}

type postServiceClient struct {
	cc *grpc.ClientConn
}

func NewPostServiceClient(cc *grpc.ClientConn) PostServiceClient {
	return &postServiceClient{cc}
}

func (c *postServiceClient) Create(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error) {
	out := new(CreatePostResponse)
	err := c.cc.Invoke(ctx, "/protobuf.PostService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) Update(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error) {
	out := new(UpdatePostResponse)
	err := c.cc.Invoke(ctx, "/protobuf.PostService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) Delete(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error) {
	out := new(DeletePostResponse)
	err := c.cc.Invoke(ctx, "/protobuf.PostService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetPostCategory(ctx context.Context, in *GetPostCategoryRequest, opts ...grpc.CallOption) (*GetPostCategoryResponse, error) {
	out := new(GetPostCategoryResponse)
	err := c.cc.Invoke(ctx, "/protobuf.PostService/GetPostCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) Find(ctx context.Context, in *FindPostRequest, opts ...grpc.CallOption) (*FindPostResponse, error) {
	out := new(FindPostResponse)
	err := c.cc.Invoke(ctx, "/protobuf.PostService/Find", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) Get(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostResponse, error) {
	out := new(GetPostResponse)
	err := c.cc.Invoke(ctx, "/protobuf.PostService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetAuthor(ctx context.Context, in *GetAuthorRequest, opts ...grpc.CallOption) (*GetAuthorResponse, error) {
	out := new(GetAuthorResponse)
	err := c.cc.Invoke(ctx, "/protobuf.PostService/GetAuthor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) FindAuthors(ctx context.Context, in *FindAuthorRequest, opts ...grpc.CallOption) (*FindAuthorResponse, error) {
	out := new(FindAuthorResponse)
	err := c.cc.Invoke(ctx, "/protobuf.PostService/FindAuthors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServiceServer is the server API for PostService service.
type PostServiceServer interface {
	//Создание записи
	Create(context.Context, *CreatePostRequest) (*CreatePostResponse, error)
	//Обновление записи
	Update(context.Context, *UpdatePostRequest) (*UpdatePostResponse, error)
	//Удаление записи
	Delete(context.Context, *DeletePostRequest) (*DeletePostResponse, error)
	//Информация о категории и связанных постах
	GetPostCategory(context.Context, *GetPostCategoryRequest) (*GetPostCategoryResponse, error)
	//Список всех постов
	Find(context.Context, *FindPostRequest) (*FindPostResponse, error)
	//Возвращает запись по SLUG
	Get(context.Context, *GetPostRequest) (*GetPostResponse, error)
	//Информация о авторе
	GetAuthor(context.Context, *GetAuthorRequest) (*GetAuthorResponse, error)
	//Список всех авторов
	FindAuthors(context.Context, *FindAuthorRequest) (*FindAuthorResponse, error)
}

// UnimplementedPostServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPostServiceServer struct {
}

func (*UnimplementedPostServiceServer) Create(ctx context.Context, req *CreatePostRequest) (*CreatePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedPostServiceServer) Update(ctx context.Context, req *UpdatePostRequest) (*UpdatePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedPostServiceServer) Delete(ctx context.Context, req *DeletePostRequest) (*DeletePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedPostServiceServer) GetPostCategory(ctx context.Context, req *GetPostCategoryRequest) (*GetPostCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostCategory not implemented")
}
func (*UnimplementedPostServiceServer) Find(ctx context.Context, req *FindPostRequest) (*FindPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}
func (*UnimplementedPostServiceServer) Get(ctx context.Context, req *GetPostRequest) (*GetPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedPostServiceServer) GetAuthor(ctx context.Context, req *GetAuthorRequest) (*GetAuthorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthor not implemented")
}
func (*UnimplementedPostServiceServer) FindAuthors(ctx context.Context, req *FindAuthorRequest) (*FindAuthorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAuthors not implemented")
}

func RegisterPostServiceServer(s *grpc.Server, srv PostServiceServer) {
	s.RegisterService(&_PostService_serviceDesc, srv)
}

func _PostService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.PostService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).Create(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.PostService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).Update(ctx, req.(*UpdatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.PostService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).Delete(ctx, req.(*DeletePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetPostCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetPostCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.PostService/GetPostCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetPostCategory(ctx, req.(*GetPostCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.PostService/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).Find(ctx, req.(*FindPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.PostService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).Get(ctx, req.(*GetPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.PostService/GetAuthor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetAuthor(ctx, req.(*GetAuthorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_FindAuthors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAuthorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).FindAuthors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.PostService/FindAuthors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).FindAuthors(ctx, req.(*FindAuthorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.PostService",
	HandlerType: (*PostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _PostService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _PostService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PostService_Delete_Handler,
		},
		{
			MethodName: "GetPostCategory",
			Handler:    _PostService_GetPostCategory_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _PostService_Find_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _PostService_Get_Handler,
		},
		{
			MethodName: "GetAuthor",
			Handler:    _PostService_GetAuthor_Handler,
		},
		{
			MethodName: "FindAuthors",
			Handler:    _PostService_FindAuthors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/post/protobuf/post.proto",
}
